spring:
  application:
    name: voting
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    database: postgresql
  flyway:
    schemas: vote
    enabled: true
    group: true
    connect-retries: 10000
    connect-retries-interval: 16s
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
logging:
  level:
    org.flywaydb: DEBUG


